Add chunksize setter to Resource(Input|Output)Stream classes
amphp/byte-stream pull request #55
Opened 2019-03-23 22:23 UTC by ostrolucky

Fixes #51

2019-03-24 10:11 UTC, kelunik requested changes

2019-03-24 10:11 UTC, kelunik commented on lib/ResourceOutputStream.php
> +        $this->chunkSize = $chunkSize;
Currently, the `$chunkSize` isn't changed inside the watcher created in the constructor, because it is captured by value there. You'll need to change that to a reference.

2019-03-24 13:36 UTC, ostrolucky commented on lib/ResourceOutputStream.php
> +        $this->chunkSize = $chunkSize;
I know, wasn't really sure I wanted to change the chunksize for watcher

2019-03-24 18:19 UTC, kelunik commented on lib/ResourceOutputStream.php
> +        $this->chunkSize = $chunkSize;
Why should the direct write chunk size change, but not the chunk size used by the watcher?

2019-03-24 23:59 UTC, ostrolucky commented on lib/ResourceOutputStream.php
> +        $this->chunkSize = $chunkSize;
my idea was that watcher processes only past writes - those that are in queue. but this is probably wrong and watcher will use old chunksize for following writes too

2019-03-25 06:12 UTC, kelunik commented on lib/ResourceOutputStream.php
> +        $this->chunkSize = $chunkSize;
Yes, exactly.

2019-03-25 09:39 UTC, ostrolucky commented on lib/ResourceOutputStream.php
> +        $this->chunkSize = $chunkSize;
Btw why is it even static if we need lot of variables from current class props anyway?

2019-03-25 10:53 UTC, kelunik commented on lib/ResourceOutputStream.php
> +        $this->chunkSize = $chunkSize;
To prevent a circular reference.

2019-03-31 11:24 UTC, ostrolucky commented
@kelunik I did requried changes. Everything allright now?

2019-03-31 14:03 UTC, kelunik approved these changes
LGTM, yes!

2019-03-31 14:37 UTC, trowski approved these changes
With the latest commit it now LGTM.

2019-03-31 14:51 UTC, merged

2019-03-31 14:51 UTC, kelunik commented
Thanks for the contribution!